name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ '-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACApU70O8N2tkqfiRqHb5aku9r/7rIj7+Dm4gvtCA1heNAAAAJiElyX3hJcl9wAAAAtzc2gtZWQyNTUxOQAAACApU70O8N2tkqfiRqHb5aku9r/7rIj7+Dm4gvtCA1heNAAAAECWBNnvmDsyn8SG3FKpIo33rQhq8XRttS/zVye6bp9JuSlTvQ7w3a2Sp+JGodvlqS72v/usiPv4ObiC+0IDWF40AAAAEm1yQERFU0tUT1AtUzJHNEtVSQECAw==-----END OPENSSH PRIVATE KEY-----' }}

      - name: Disable strict host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Sync project to VPS
        run: |
          rsync -avz \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.github' \
            -e "ssh -p ${{ '22' }}" \
            ./ ${{ 'root' }}@${{ '164.92.105.164' }}:/home/${{ 'root' }}/my-portfolio

      - name: Remote deploy & restart
        run: |
          ssh -p ${{ '22' }} ${{ 'root' }}@${{ '164.92.105.164' }} << 'EOF'
            cd /home/${{ 'root' }}/my-portfolio
            npm install --production
            pm2 restart my-portfolio || pm2 start npm --name my-portfolio -- start
          EOF
