name: CI/CD Pipeline

on:
  push:
    branches:
      - main
# Removed misplaced steps block. Steps are already defined under jobs: build and jobs: deploy.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build 

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIClTvQ7w3a2Sp+JGodvlqS72v/usiPv4ObiC+0IDWF40 mr@DESKTOP-S2G4KUI' }}

      - name: Disable strict host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Sync project to VPS
        run: |
          rsync -avz \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.github' \
            -e "ssh -p ${{ '22'}}" \
            ./ ${{ 'root' }}@${{ '164.92.105.164' }}:/home/${{ 'root' }}/my-portfolio

      - name: Remote deploy & restart
        run: |
          ssh -p ${{ '22' }} ${{ 'root'}}@${{ '164.92.105.164' }} << 'EOF'
            cd /home/${{ 'root' }}/my-portfolio
            npm install --production
            pm2 restart my-portfolio || pm2 start npm --name my-portfolio -- start
          EOF
